version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: balancetracker-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: balancetracker
      POSTGRES_USER: balancetracker
      POSTGRES_PASSWORD: balancetracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - balancetracker-network

volumes:
  postgres_data:
    driver: local

networks:
  balancetracker-network:
    driver: bridge
